service: oc-logger-backend

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

functions:
  oauth:
    handler: ./OAuth/oauth.invoke
    environment:
      CONSUMER_KEY: ${env:CONSUMER_KEY}
      CONSUMER_SECRET: ${env:CONSUMER_SECRET}

  getOAuthToken:
    handler: ./OAuth/requestToken.invoke
    environment:
      OAUTH_CALLBACK: ${env:OAUTH_CALLBACK}
    events:
      - http:
          path: oauth/requestToken
          method: get

  getAccessToken:
    handler: ./OAuth/accessToken.invoke
    events:
      - http:
          path: oauth/accessToken
          method: post